---
title: "`r gsub('.Rmd', ' ', gsub('_', ' ', knitr::current_input()))`"
author: "Holly Beale"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_knit$set(root.dir = "/data/projects/gitCode/umend_qc_publication/notebooks")

library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(cowplot)
library(gridGraphics)
library(RColorBrewer)
library(viridis)
library(ggrepel)

```

# Settings

```{r}

library(RColorBrewer)

source_palette <- brewer.pal(12, "Paired")
cb_dark_green <- source_palette[4]
cb_light_green <- source_palette[3]


raw_names_for_read_types <-  c("not_mapped", "Multimapped_read_count", "duplicate_reads", "non_exonic_reads", "UMEND")
intermediate_names_for_read_types = c("Not mapped", "Multi-mapped", "Duplicate reads", "Non exonic reads", "UMEND")
better_names_for_read_types <- c("Not mapped", "Multi-mapped", "Duplicate", "Non exonic", "UMEND")


category_colors <- c(grey(0.5), "blue", cb_light_green, grey(0.7), cb_dark_green) 
names(category_colors) <- intermediate_names_for_read_types

```


### Read counts
```{r}
read_counts_in_subsets <- read_tsv(file.path("../data/read_counts.txt"), 
                         col_names = c("sample_id", "count_type", "read_count")) %>%
  spread(count_type, read_count) %>%
  mutate(parent_sample = gsub("_est.*$", "", sample_id))


```


# Groom

```{r}

complete_counts <- read_counts_in_subsets %>%
  mutate(Mapped_read_count = Multimapped_read_count + Uniquely_mapped_read_count) %>%
  select(-Uniquely_mapped_read_count) 


```

### QC

```{r}

# effect of excluding NA, which are usually samples without four measurements
nrow(na.omit(complete_counts))
nrow((complete_counts))


```

## Simplify names

```{r}

read_counts <- complete_counts %>%
  rename(UM = Mapped_read_count,
         UMND = Uniquely_mapped_non_duplicate_read_count)
    

```

## Calculate fractions of read types

```{r}

orderByTotalReads <- read_counts %>% arrange(desc(total_sequences)) %>%	.$sample_id
read_counts_with_slices <- read_counts %>% 
  arrange(desc(total_sequences)) %>% 
  mutate(pct_UMEND = UMEND / total_sequences,
         Percent_duplicates = 1 - (UMND / UM), 
         not_mapped = total_sequences - UM,
         duplicate_reads = UM - UMND,
         non_exonic_reads = UMND - UMEND,
         sum_slices = UMEND + non_exonic_reads + duplicate_reads + not_mapped)

```


## Convert to long form

```{r}

read_counts_with_percentages <- read_counts_with_slices %>% 
			select(sample_id,
			       parent_sample,
			       not_mapped,
			       duplicate_reads,
			       non_exonic_reads,
			       UMEND,
			       Multimapped_read_count,
			       UM,
			       Percent_duplicates,
			       pct_UMEND,
			       total_sequences) %>%
			gather(read_type, read_count, not_mapped, duplicate_reads, non_exonic_reads, UMEND, Multimapped_read_count) %>%
			mutate(read_type = intermediate_names_for_read_types[match(read_type, raw_names_for_read_types)],
			       read_type = factor(read_type,
			                          levels = intermediate_names_for_read_types),
			       sample_id = factor(sample_id, levels = orderByTotalReads),
			       read_countM = read_count / 1e6,
			       divisor_for_percent = ifelse(read_type=="Multi-mapped", UM, total_sequences),
			       percent_of_total = read_count / divisor_for_percent)


# table(read_counts_with_percentages$read_type)

```

# Plot pct dupes per total depth
```{r}

ggplot(read_counts_with_percentages) + geom_line(aes(x=total_sequences/1E6, y=percent_of_total, color=parent_sample)) + ggtitle("Fraction of duplicate reads increases with depth") + scale_color_brewer(palette = "Set1") + facet_wrap(~read_type)
  
  
  
  
```